# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BreakGlass < Formula
  desc "break-glass is a simple tool to manage short lived AWS credentials"
  homepage "https://github.com/errm/break-glass"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/errm/break-glass/releases/download/v0.1.4/break-glass_Darwin_x86_64.tar.gz"
      sha256 "acd1305878161178a6f4e90621cb75770464b49ac2b0e01d92cb3e0dc408a031"

      def install
        bin.install "break-glass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/errm/break-glass/releases/download/v0.1.4/break-glass_Darwin_arm64.tar.gz"
      sha256 "ca62b4cea3dadf615fdfcf08d4403c2e520bb7c61fcd979378839642771bed84"

      def install
        bin.install "break-glass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/errm/break-glass/releases/download/v0.1.4/break-glass_Linux_arm64.tar.gz"
      sha256 "0b89cadcb4c4d0218bf428d73a40cdbf01ae1668a75d2cbd20504b3c2ec65a5b"

      def install
        bin.install "break-glass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/errm/break-glass/releases/download/v0.1.4/break-glass_Linux_x86_64.tar.gz"
      sha256 "17feb5a11cf98eb454e8933f908db582fdd27b6aba4eb0730e19c815bf64de79"

      def install
        bin.install "break-glass"
      end
    end
  end
end
