# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BreakGlass < Formula
  desc "break-glass is a simple tool to manage short lived AWS credentials"
  homepage "https://github.com/errm/break-glass"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/errm/break-glass/releases/download/v0.1.3/break-glass_Darwin_arm64.tar.gz"
      sha256 "d7abbade1a8ec680556f8db69b80753dd21254837df99bc977222a26b6e6c8d8"

      def install
        bin.install "break-glass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/errm/break-glass/releases/download/v0.1.3/break-glass_Darwin_x86_64.tar.gz"
      sha256 "98853be068f0059ed9d8e2471e45880eecd8adc7df03902eaf158d583600057e"

      def install
        bin.install "break-glass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/errm/break-glass/releases/download/v0.1.3/break-glass_Linux_x86_64.tar.gz"
      sha256 "a6af6fe34869b47868dac43525de6a3f0e87529726ffea27b93b6be2ca6c11f9"

      def install
        bin.install "break-glass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/errm/break-glass/releases/download/v0.1.3/break-glass_Linux_arm64.tar.gz"
      sha256 "7b5ebaf5b4169ae5495e78ffae689c4aa71f1c76135e0a9b4a8659f55bd642de"

      def install
        bin.install "break-glass"
      end
    end
  end
end
